-- Insert data for currency
INSERT INTO Currency(symbol, name) VALUES ('AUD', 'Dola Uc');
INSERT INTO Currency(symbol, name) VALUES ('CAD', 'Dola Canada');
INSERT INTO Currency(symbol, name) VALUES ('CHF', 'Franc Thuy Sy');
INSERT INTO Currency(symbol, name) VALUES ('CNY', 'Nhan dan te');
INSERT INTO Currency(symbol, name) VALUES ('DKK', 'Krone Dan Mach');
INSERT INTO Currency(symbol, name) VALUES ('EUR', 'Euro chau Au');
INSERT INTO Currency(symbol, name) VALUES ('GBP', 'Bang Anh');
INSERT INTO Currency(symbol, name) VALUES ('HKD', 'Dola HongKong');
INSERT INTO Currency(symbol, name) VALUES ('INR', 'Rupee An Do');
INSERT INTO Currency(symbol, name) VALUES ('JPY', 'Yen Nhat');
INSERT INTO Currency(symbol, name) VALUES ('KRW', 'Won Han Quoc');
INSERT INTO Currency(symbol, name) VALUES ('KWD', 'Dinar Kuwait');
INSERT INTO Currency(symbol, name) VALUES ('LAK', 'Kip Lao');
INSERT INTO Currency(symbol, name) VALUES ('MYR', 'Ringgit Malaysia');
INSERT INTO Currency(symbol, name) VALUES ('NOK', 'Krone NaUy');
INSERT INTO Currency(symbol, name) VALUES ('NZD', 'Dola New Zealand');
INSERT INTO Currency(symbol, name) VALUES ('RUP ', 'Rup Nga');
INSERT INTO Currency(symbol, name) VALUES ('SAR', 'Riyal A Rap Xe Ut');
INSERT INTO Currency(symbol, name) VALUES ('SEK', 'Krona Thuy Dien');
INSERT INTO Currency(symbol, name) VALUES ('SGD', 'Dola Singgapore');
INSERT INTO Currency(symbol, name) VALUES ('THB', 'Baht Thai');
INSERT INTO Currency(symbol, name) VALUES ('USD', 'Dola My');


-- Insert data for bank
INSERT INTO bank(id, name) VALUES (1, 'Vietcombank	 ');
INSERT INTO bank(id, name) VALUES (2, 'Agribank	 ');
INSERT INTO bank(id, name) VALUES (3, 'ACB	 ');
INSERT INTO bank(id, name) VALUES (4, 'Vietinbank	 ');
INSERT INTO bank(id, name) VALUES (5, 'BIDV	 ');
INSERT INTO bank(id, name) VALUES (6, 'Dong A');
INSERT INTO bank(id, name) VALUES (7, 'SCB	 ');
INSERT INTO bank(id, name) VALUES (8, 'HSBC	 ');
INSERT INTO bank(id, name) VALUES (9, 'NCB	 ');
INSERT INTO bank(id, name) VALUES (10, 'Sacombank	 ');
INSERT INTO bank(id, name) VALUES (11, 'TPBank	 ');
INSERT INTO bank(id, name) VALUES (12, 'EximBank	 ');
INSERT INTO bank(id, name) VALUES (13, 'VIB	 ');
INSERT INTO bank(id, name) VALUES (14, 'SHB	 ');
INSERT INTO bank(id, name) VALUES (15, 'OCB	 ');
INSERT INTO bank(id, name) VALUES (16, 'Shinhan Bank	 ');
INSERT INTO bank(id, name) VALUES (17, 'Vietbank	 ');
INSERT INTO bank(id, name) VALUES (18, 'PG Bank	 ');
INSERT INTO bank(id, name) VALUES (19, 'MSB	 ');
INSERT INTO bank(id, name) VALUES (20, 'ABBank	 ');
INSERT INTO bank(id, name) VALUES (21, 'Citibank	 ');
INSERT INTO bank(id, name) VALUES (22, 'MBBank	 ');
INSERT INTO bank(id, name) VALUES (23, 'LienVietPostBank	 ');
INSERT INTO bank(id, name) VALUES (24, 'SeABank	 ');
INSERT INTO bank(id, name) VALUES (25, 'Standard Chartered	 ');
INSERT INTO bank(id, name) VALUES (26, 'PVcomBank	 ');
INSERT INTO bank(id, name) VALUES (27, 'ANZ	 ');
INSERT INTO bank(id, name) VALUES (28, 'Co-opbank	 ');
INSERT INTO bank(id, name) VALUES (29, 'BIDC	 ');
INSERT INTO bank(id, name) VALUES (30, 'UOB	 ');
INSERT INTO bank(id, name) VALUES (31, 'First Bank	 ');
INSERT INTO bank(id, name) VALUES (32, 'Woori Bank	 ');
INSERT INTO bank(id, name) VALUES (33, 'Nam A Bank	 ');
INSERT INTO bank(id, name) VALUES (34, 'Saigonbank	 ');
INSERT INTO bank(id, name) VALUES (35, 'Bac A Bank	 ');
INSERT INTO bank(id, name) VALUES (36, 'HDBank	 ');
INSERT INTO bank(id, name) VALUES (37, 'Viet Capital Bank	 ');
INSERT INTO bank(id, name) VALUES (38, 'VietABank	 ');
INSERT INTO bank(id, name) VALUES (39, 'GPBank	 ');
INSERT INTO bank(id, name) VALUES (40, 'KienLong Bank	 ');
INSERT INTO bank(id, name) VALUES (41, 'OceanBank	 ');
INSERT INTO bank(id, name) VALUES (42, 'CBBank	 ');
INSERT INTO bank(id, name) VALUES (43, 'BAOVIET Bank	 ');
INSERT INTO bank(id, name) VALUES (44, 'VBSP	 ');
INSERT INTO bank(id, name) VALUES (45, 'VDB	 ');
INSERT INTO bank(id, name) VALUES (46, 'Public Banz Nam	 ');
INSERT INTO bank(id, name) VALUES (47, 'Indovina Bank	 ');
INSERT INTO bank(id, name) VALUES (48, 'VRB	 ');
INSERT INTO bank(id, name) VALUES (49, 'HongLeong Bank	 ');

-- Insert data for currency
