version: "3.9"
services:
  web:
    image: warehouse-service
    container_name: warehouse-service
    build:
      context: .
    ports:
        - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://10.5.0.9:5432/ware_house
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SERVICES_CRAWLER_BASEURL=http://10.5.0.8:8080/
    networks:
      default:
         ipv4_address: 10.5.0.5
networks:
  default:
    name: drawler_backend
    external: true
