version: "3.6"
services:
  postgresql:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
    volumes:
      - pgData:/var/lib/postgresql/data
    command: -p 5433
    networks:
      backend:
        ipv4_address: 10.5.0.9
  web:
    image: drawler
    container_name: drawler-app
    build:
      context: .
    ports:
        - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://10.5.0.9:5433/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgresql
    networks:
      backend:
        ipv4_address: 10.5.0.8
volumes:
  pgData:
networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1